services:
  - type: web
    name: nazara-smart-stock-watchlist
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: FMP_API_KEY
        sync: false
